# Generated by Django 4.0.2 on 2022-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_details_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
